# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to the root build.gradle expandProps map.

# Gradle
org.gradle.daemon                    = true
org.gradle.jvmargs                   = -Xmx3G
org.gradle.parallel                  = true
org.gradle.caching                   = true

# Plugins
modmuss50_mod_publish_version        = 0.4.0
spongepowered_mixin_version          = 0.7-SNAPSHOT
fabric_loom_version                  = 1.10-SNAPSHOT
parchment_minecraft                  = 1.21.1
parchment_version                    = 2024.11.17
neoform_version                      = 1.21.1-20240808.144430

# Project
modrinthID				             = AOs8oaMT
curseforgeID			             = 514628
projectSlug				             = arachnids

# Common
java_version                         = 21
minecraft_version                    = 1.21.1

# NeoForge
loader_version_range                 = [3,)
mapping_channel                      = official
mapping_version                      = 1.21.1
minecraft_version_range              = [1.21.1, 1.21.2)
neo_moddev                           = 2.0.112
neo_version                          = 21.1.217
neo_version_range                    = [21,)

# Fabric
fabric_version                       = 0.116.6+1.21.1
fabric_loader_version                = 0.17.2

# Libs
modmenu_version                      = 11.0.2
azurelib_version                     = 3.1.8

# Mod options
group                                = mod.azure.arachnids
mod_name                             = Arachnids
mod_author                           = AzureDoom
mod_id                               = arachnids
mod_license                          = MIT
mod_description                      = Arachnids is a mod based on the first Starship Troopers movie and 2005 game about an alien race of bugs. This mod brings those creatures into the Minecraft world, where the bugs control the deserts of the Overworld.
mod_credits                          = AzureDoom, Wolverbyte
mod_logo                             = icon.png
mod_url                              = https://www.curseforge.com/minecraft/mc-mods/arachnids
mod_issues                           = https://github.com/AzureDoom/Arachnids-ML/issues
mod_sources                          = https://github.com/AzureDoom/Arachnids-ML
version                              = 0.3.0
